oam/urls.py
from django.conf.urls import url

from . import views

app_name = "oam"


urlpatterns = [
    url(r'^invoices/$', views.index, name="invoices_index"),
    url(r'^invoices/new$', views.new, name="invoices_new"),
    url(r'^invoice/(?P<pk>[0-9]+)$', views.detail, name="invoice_detail"),
    url(r'^invoice/(?P<pk>[0-9]+)/edit$', views.edit, name="invoice_edit"),
    url(r'^invoice/(?P<pk>[0-9]+)/new/transaction$',
        views.new_transaction, name="invoice_new_transaction"),
    url(r'^invoice/(?P<pk>[0-9]+)/transaction/(?P<transaction_id>[0-9]+)/edit$',
        views.edit_transaction, name="invoice_edit_transaction"),
    url(r'^invoice/(?P<pk>[0-9]+)/notes$',
        views.notes, name="invoice_notes"),
    url(r'^invoice/(?P<pk>[0-9]+)/new/note$',
        views.new_note, name="invoice_new_note"),
]

tagoretown/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^oam/(?P<customer_url_id>[a-zA-Z0-9]+)/',
        include('oam.urls')),
    url(r'^admin/', admin.site.urls),
]

oam/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.contrib.contenttypes.fields \
    import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
import locale

# Create your models here.
try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass


class Note(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    isEditable = models.BooleanField(default=True)
    isRemovable = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date_added"]

    def __str__(self):
        return self.title


class Image(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    title = models.CharField(max_length=150)
    image_cdn_url = models.URLField("Image URL", max_length=200)
    notes = GenericRelation(Note)

    def __str__(self):
        return self.title


class Customer(models.Model):
    name = models.CharField(max_length=150)
    corp = models.CharField(max_length=255, blank=True)
    corp_url_id = models.CharField(
        max_length=255,
        null=False,
        db_index=True,
        unique=True)
    email = models.EmailField(max_length=254, db_index=True)
    password = models.CharField(max_length=255)
    notes = GenericRelation(Note)
    date_added = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.corp)

    class Meta:
        ordering = ['name']


class CustomerAdmin(admin.ModelAdmin):
    list_display = ('name', 'corp', 'email')

    class Meta:
        ordering = ['-date_added']


class Invoice(models.Model):
    customer = models.ForeignKey('Customer')
    number = models.CharField('Invoice #', max_length=50)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    paid = models.BooleanField(default=False)
    void = models.BooleanField(default=False)
    invoice_date = models.DateField()
    due_date = models.DateField(default=None, null=True, blank=True)
    date_paid = models.DateField(default=None, null=True, blank=True)
    notes = GenericRelation(Note)
    date_added = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.number

    def status(self):
        if(self.paid):
            retval = "Paid"
        elif(self.due_date is not None and
             self.due_date < timezone.now().date()):
            retval = "Overdue"
        else:
            retval = "Unpaid"

        return retval

    def balance_due(self):
        transaction_total = getattr(self, 'transaction_total', None)
        if not transaction_total:
            transaction_total = self.transaction_set.aggregate(
                models.Sum('amount'))['amount__sum'] or 0
        return self.amount - transaction_total


class Transaction(models.Model):
    invoice = models.ForeignKey('Invoice')
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    payment_type = models.CharField(max_length=30, default="Cheque")
    notes = GenericRelation(Note)
    images = GenericRelation(Image)
    date_added = models.DateTimeField("Transaction Date", blank=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Transaction for {0} on {1:%B %d, %Y}'.format(
            self.invoice.number,
            self.date_added)

    class Meta:
        ordering = ['-date_added']


class TransactionAdmin(admin.ModelAdmin):
    list_display = [
        'date_added',
        'invoice_number',
        'invoice_amount',
        'formatted_amount', ]

    def invoice_number(self, obj):
        return obj.invoice.number

    invoice_number.short_description = "Invoice Number"

    def formatted_amount(self, obj):
        return locale.currency(obj.amount, grouping=True)

    formatted_amount.short_description = "Transaction Amount"
    formatted_amount.admin_order_field = "amount"

    def invoice_amount(self, obj):
        return locale.currency(obj.invoice.amount, grouping=True)

    invoice_amount.short_description = "Invoiced Amount"
    invoice_amount.admin_order_field = "invoice__amount"

oam/forms.py
from django import forms
from .models import Invoice, Note, Transaction


class InvoiceForm(forms.ModelForm):

    class Meta:
        model = Invoice
        fields = ['number', 'amount', 'paid',
                  'customer', 'due_date', 'date_paid', ]
        localized_fields = ('amount', 'due_date', )


class TransactionForm(forms.ModelForm):
    transaction_note = forms.CharField(
        label='Transaction Note',
        widget=forms.Textarea,
        required=False)

    class Meta:
        model = Transaction
        fields = ['amount', 'payment_type', ]

        localized_fields = ('amount', 'date_added', )


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['text', ]

        labels = {
            'text': 'Notes',
        }

oam/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.db.models import Prefetch, Count, Sum
from django.utils import timezone
from oam.models import Customer, Invoice, Transaction, Note
from .forms import InvoiceForm, TransactionForm, NoteForm

return_dict = {
    'title': None,
    'customer_name': None,
    'customer_url_id': None,
}


def Http404(request):
    render(request, r'oam/error404.html')


def index(request, customer_url_id):
    qs_invoices_base = Invoice.objects.order_by("-date_added").annotate(
        num_of_transactions=Count('transaction'),
        transaction_total=Sum('transaction__amount')
    ).only(
        'date_added', 'amount', 'number')
    customer = get_object_or_404(
        Customer.objects
        .prefetch_related(
            Prefetch("invoice_set",
                     queryset=qs_invoices_base.filter(paid=True),
                     to_attr="invoices_paid"),
            Prefetch("invoice_set",
                     queryset=qs_invoices_base.filter(paid=False),
                     to_attr="invoices_unpaid")).only('corp'),
        corp_url_id=customer_url_id)

    return_dict.update({
        'title': 'Invoices',
        'customer_name': customer.corp,
        'invoices_paid': customer.invoices_paid[:5],
        'invoices_unpaid': customer.invoices_unpaid[:5],
        'customer_url_id': customer_url_id,
    })
    return render(request, r'oam/index.html', return_dict)


def detail(request, customer_url_id, pk):
    selected_invoice = get_object_or_404(
        Invoice.objects
        .only('invoice_date', 'due_date', 'amount', 'customer__corp')
        .annotate(number_of_notes=Count('notes'))
        .select_related('customer')
        .prefetch_related(
            Prefetch('transaction_set',
                     queryset=Transaction.objects.order_by(
                         "-date_added"),
                     to_attr="transactions")), id=pk)
    return render(request, r'oam/invoice/detail.html', {
        'title': 'Invoice: {0}'.format(selected_invoice.number),
        'browser_title': 'Invoice# {0}'.format(selected_invoice.number),
        'invoice': selected_invoice,
        'related_transactions': selected_invoice.transactions,
        'customer_url_id': selected_invoice.customer.corp_url_id,
        'customer_name': selected_invoice.customer.corp,
    })


def edit(request, customer_url_id, pk):
    invoice = Invoice.objects.get(pk=pk)
    form = InvoiceForm(request.POST or None, instance=invoice)
    if(request.POST):
        saved_invoice = form.save(commit=False)

        saved_invoice.paid = bool(form.cleaned_data['date_paid'])

        saved_invoice.save()
        return HttpResponseRedirect(
            reverse("oam:invoice_detail",
                    kwargs={'customer_url_id':
                            saved_invoice.customer.corp_url_id,
                            'pk': pk}))

    return_dict.update({
        'title': 'Edit Invoice# {}'.format(invoice.number),
        'form': form,
        'customer_url_id': customer_url_id,
        'pk': pk
    })
    return render(request, "oam/invoice/edit.html", return_dict)


def new(request, customer_url_id):
    form = InvoiceForm(request.POST or None, initial={
                       'customer': Customer.objects.get(
                           corp_url_id=customer_url_id)})
    if(request.POST):
        if form.is_valid():
            new_invoice = form.save(commit=False)
            new_invoice.balance_due = new_invoice.amount
            new_invoice.save()
            return HttpResponseRedirect(
                reverse("oam:invoice_detail",
                        kwargs={'customer_url_id':
                                new_invoice.customer.corp_url_id,
                                'pk': new_invoice.pk}))

    return_dict.update({
        'title': 'New Invoice',
        'form': form,
        'customer_url_id': customer_url_id
    })
    return render(request, "oam/invoice/new.html", return_dict)


def new_transaction(request, customer_url_id, pk):
    invoice = Invoice.objects.only('number').get(pk=pk)
    form = TransactionForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            invoice.transaction_set.create(
                amount=form.cleaned_data['amount'],
                payment_type=form.cleaned_data['payment_type'],
                date_added=timezone.now())
            invoice.save()
            return HttpResponseRedirect(
                reverse("oam:invoice_detail",
                        kwargs={'customer_url_id':
                                customer_url_id,
                                'pk': pk}))
    else:
        return_dict.update({
            'super_template': "oam/modal_layout.html",
            })

    return_dict.update({
        'title': 'New Transaction for Invoice# {}'.format(invoice.number),
        'form': form,
        'customer_url_id': customer_url_id,
        'post_url': reverse("oam:invoice_new_transaction",
                            kwargs={'customer_url_id': customer_url_id,
                                    'pk': pk})
    })
    return render(request, 'oam/transaction/new.html', return_dict)


def edit_transaction(request, customer_url_id, pk):
    pass


def new_note(request, customer_url_id, pk):
    invoice = Invoice.objects.only('number').get(pk=pk)
    form = NoteForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            invoice.notes.create(text=form.cleaned_data['text'])
            invoice.save()
            return HttpResponseRedirect(
                reverse("oam:invoice_detail",
                        kwargs={'customer_url_id':
                                customer_url_id,
                                'pk': pk}))

    return_dict.update({
        'title': 'New Note for Invoice# {}'.format(invoice.number),
        'form': form,
        'customer_url_id': customer_url_id,
        'super_template': "oam/modal_layout.html",
        'post_url': reverse("oam:invoice_new_note",
                            kwargs={'customer_url_id': customer_url_id,
                                    'pk': pk})
    })
    return render(request, "oam/note/new.html", return_dict)


def notes(request, customer_url_id, pk):
    selected_invoice = Invoice.objects.only('number').prefetch_related(
        Prefetch('notes',
                 queryset=Note.objects.only(
                     'text', 'date_added')
                 .order_by("-date_added"))) \
        .get(pk=pk)
    return_dict.update({
        'title': 'Notes for Invoice# {}'.format(selected_invoice.number),
        'notes': selected_invoice.notes.all(),
        'customer_url_id': customer_url_id,
        'super_template': "oam/modal_layout.html",
    })

    return render(request, "oam/note/list.html", return_dict)

oam/templates/oam/detail.html
{% extends "oam/layout.html" %}
{% load staticfiles %}

{% load formatfilters %}

{% block styling %}	
		<style type="text/css" media="screen,projection">
			div#content_section div.row{
				margin-bottom: 0.5em;
			}
			.text-white
			{
				color: #ffffff;
			}
			.label{
				font-size: 100%;
				line-height: 2.2;
			}
			.label-danger{
				background-color: #ff4f52;
			}
			.label-success{
				background-color: #06A209;
			}
		</style>
{% endblock %}

{% block js %}
	<script type="text/javascript">
	var modalUI = null;

	$(document).ready(function(){
		modalUI = $("div#relatedModal");
		modalUI.modal({show: false});
	});

	function relatedModalUI (sender) {
		var senderObject = $(sender);
		var ajaxUrl = $(senderObject).data("ajax-url");

		modalUI.load(
			ajaxUrl,
			function(){
				modalUI.modal({show: true});
			});
	}
	</script>
	
{% endblock js %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<a class="breadcrumbs" href="{% url "oam:invoices_index" invoice.customer.corp_url_id %}">
						Dashboard
					</a>
					&gt; Invoice Details
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-buttons">
					<div class="well well-sm">
						<a href="{% url "oam:invoice_edit" customer_url_id invoice.pk %}" class="btn btn-default">Edit Invoice</a>
						<button class="btn btn-default" data-ajax-url="{% url "oam:invoice_new_note" customer_url_id invoice.pk %}" type="button" onclick="relatedModalUI(this)">Add Note</button>
						<button class="btn btn-default" data-ajax-url="{% url "oam:invoice_notes" customer_url_id invoice.pk %}" type="button" onclick="relatedModalUI(this)">Note{{invoice.number_of_notes|pluralize}} ({{invoice.number_of_notes}})</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Invoice Date</span></div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ invoice.invoice_date|date:"m/j/Y" }}</div>
						</div>
					</div>
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Company</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ invoice.customer.corp|title }}</div>
						</div>
					</div>
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Amount</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ invoice.amount|currency }}</div>
						</div>
					</div>
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Balance Due</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ invoice.balance_due|currency }}</div>
						</div>
					</div>
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Due Date</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">{{ invoice.due_date|date:"m/j/Y"|default:"No due date"  }}</div>
						</div>
					</div>
					<div class="col-md-2 col-lg-2 col-sm-12 col-xs-12">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bg-default text-uppercase h4" style="border-bottom: 2px solid #fff; padding-bottom: 0.2em">Status</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-uppercase {% ifequal invoice.status "Unpaid" %}text-success{% endifequal %}{% ifequal invoice.status "Paid" %}text-success{% endifequal %}">{{ invoice.status }}</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<table class="table table-condensed table-striped table-bordered">
						<caption class="h3">Related Transactions</caption>
						<thead>
							<tr>
								<th class="h4" style="width: 5%"></th>
								<th class="h4" scope="col">Date</th>
								<th class="h4" scope="col">Amount</th>
								<th class="h4" scope="col">Payment Method</th>
								<th class="h4" style="width: 5%"></th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="5">
									<button class="btn btn-sm btn-primary" data-ajax-url="{% url "oam:invoice_new_transaction" customer_url_id invoice.pk %}" type="button" onclick="relatedModalUI(this)">Record Transaction</button>
								</td>
							</tr>
						</tfoot>
						<tbody>
							{% for transaction in related_transactions %}
								<tr>
									<td class="text-right">
										<button class="btn btn-default btn-sm" title="View">
											<i class="fa fa-sm fa-file-o"></i>
											</button>
									</td>
									<td>{{ transaction.date_added|date:"m/j/y" }}</td>
									<td>{{ transaction.amount|currency }}</td>
									<td>{{ transaction.payment_type }}</td>
									<td>
										<button class="btn btn-danger btn-sm" title="Delete"><i class="fa fa-sm fa-trash"></i></button>
									</td>
								</tr>
							{% empty %}
								<tr>
									<td colspan="5">No related transactions recorded</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div id="relatedModal" class="modal fade" role="dialog">
	</div>
{% endblock content %}

oam/templates/oam/edit_invoice.html
{% extends "oam/layout.html" %}
{% load staticfiles %}

{% block styling %}
    <link rel="stylesheet" type="text/css" href="{% static "app/css/detail.css" %}"/>  
{% endblock styling %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="POST" id="frmEditInvoice">
                {% csrf_token %}
                <div class="row form-buttons">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <button class="btn btn-success">Save</button>
                      	<a href="{% url "oam:invoice_detail" customer_url_id pk %}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 entry-field">
                        {{ form.number.label_tag }}
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 entry-value">
                        {{ form.number }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 entry-field">
                        {{ form.customer.label_tag }}
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 entry-value">
                        {{ form.customer }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 entry-field">
                        {{ form.amount.label_tag }}
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 entry-value">
                        {{ form.amount }}
                    </div>
                </div>    
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 entry-field">
                        {{ form.paid.label_tag }}
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 entry-value">
                        {{ form.paid }}
                    </div>
                </div>   
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 entry-field">
                        {{ form.due_date.label_tag }}
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 entry-value">
                        {{ form.due_date }}
                    </div>
                </div>            
            </form>
        </div>
    </div>
{% endblock content %}

{% block js %}

<script type="text/javascript">
$(document).ready(function(){
    $("form#frmEditInvoice input:text, form#frmEditInvoice select, form#frmEditInvoice textarea").addClass("form-control");
})
</script>
    
{% endblock js %}

oam/templates/oam/error404.html
{% extends "oam/layout.html" %}

{% block content %}
    Customer not found
{% endblock content %}

oam/templates/oam/index.html
{% extends "oam/layout.html" %}

{% block content %}
	<a href="{% url "oam:invoices_new" customer_url_id %}" class="btn btn-primary">New Invoice</a>
	{% if invoices_unpaid %}
		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
				<h3 class="h3">Outstanding Invoices</h3>
				{% include "oam/invoice/list.html" with invoice_list=invoices_unpaid %}
			</div>
		</div>	
	{% endif %}

	{% if invoices_paid %}	
		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
				<h3 class="h3">Paid Invoices</h3>
				{% include "oam/invoice/list.html" with invoice_list=invoices_paid %}
			</div>
		</div>
	{% endif %}
{% endblock %}

{% block styling %}
<style type="text/css">
	div#content_section 
		table[data-listing-type="invoices"] 
			tbody 
				tr 
					td:first-child,
	div#content_section 
		table[data-listing-type="invoices"] 
			td[data-data-type="currency"]
	{
						text-align: right;
	}
</style>
{% endblock %}

oam/templates/oam/invoice_list.html
{% load formatfilters %}

{% if invoice_list %}
    <table class="table table-bordered table-striped" data-listing-type="invoices">
        <thead>
            <tr>
                <th scope="col" style="width:12%">Invoice #</th>
                <th scope="col">Date</th>
                <th scope="col">Amount</th>
                <th scope="col">Balance Due</th>
            </tr>
        </thead>
        <tbody>
            {% for invoice in invoice_list %}
            <tr>
                <td><a href="{% url "oam:invoice_detail" invoice.customer.corp_url_id invoice.id %}">{{ invoice.number }} ({{ invoice.num_of_transactions }})</a></td>
                <td>{{ invoice.date_added|date:"m/j/y" }}</td>
                <td data-data-type="currency">{{ invoice.amount|currency }}</td>
                <td data-data-type="currency">{{ invoice.balance_due|currency }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>                    
{% else %}
    <p>No invoices available</p>
{% endif %}

oam/templates/oam/invoice_new_note.html
{% extends super_template|default:"oam/layout.html" %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block styling %}
    <link rel="stylesheet" type="text/css" href="{% static "app/css/detail.css" %}"/>  
    <style type="text/css">
        div#content_section span.k-dropdown {
            width: 100%;
        }
    </style>
{% endblock styling %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="POST" action="{{ post_url|default:None }}" id="frmInvoice_NewNote">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                        {{ form.text.label_tag }}
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                        {{ form.text|add_class:"form-control" }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-buttons">
                        <button class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-default">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

oam/templates/oam/new_invoice.html
{% extends "oam/layout.html" %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block styling %}
    <link rel="stylesheet" type="text/css" href="{% static "app/css/detail.css" %}"/>  
    <style type="text/css">
        div#content_section span.k-dropdown {
            width: 100%;
        }
    </style>
{% endblock styling %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form method="POST" id="frmNewInvoice">
                {% csrf_token %}
                <fieldset class="well">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                            {{ form.number.label_tag }}
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                            {{ form.number|add_class:"form-control" }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                            {{ form.customer.label_tag }}
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                            {{ form.customer|append_attr:"style:width:100%'"  }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                            {{ form.amount.label_tag }}
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                            {{ form.amount }}
                        </div>
                    </div>    
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                            {{ form.paid.label_tag }}
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                            {{ form.paid }}
                        </div>
                    </div>   
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-field">
                            {{ form.due_date.label_tag }}
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 entry-value">
                            {{ form.due_date }}
                        </div>
                    </div>  

                    <div class="row form-buttons">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <button class="btn btn-success">Save</button>
                            <a href="{% url "oam:invoices_index" customer_url_id %}" class="btn btn-default">Cancel</a>
                        </div>
                    </div> 
                </fieldset>         
            </form>
        </div>
    </div>
{% endblock content %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){
    $("form#frmNewInvoice input[id$=_date]").kendoDatePicker();
    $("form#frmNewInvoice select").kendoDropDownList({
        width: "100"
    });
    $("form#frmNewInvoice input[id$=amount]").kendoNumericTextBox({
       format: "c"
    });
})
</script>
    
{% endblock js %}

oam/templates/oam/note_list.html
{% extends super_template|default:"oam/layout.html" %}

{% block content %}
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">	
		{% include "oam/invoice_note.html" with notes=notes %}
		</div>
	</div>
{% endblock content %}